# Generated by Django 3.0 on 2021-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField()),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
    ]
